services:
  docusign-api:
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: docusign-api
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      - DOCUSIGN_PRIVATE_KEY_PATH=/run/secrets/docusign_private_key
    secrets:
      - docusign_private_key
    restart: unless-stopped
networks:
  default:
    driver: bridge

secrets:
  docusign_private_key:
    file: ./private.pem