services:
  docusign-api:
    image: docusign-api:prod
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      - DOCUSIGN_PRIVATE_KEY_PATH=/run/secrets/docusign_private_key
    secrets:
      - docusign_private_key

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  default:
    driver: overlay

secrets:
  docusign_private_key:
    external: true